//#############################################################################
//
// FILE:   main.c
//
// TITLE:  LED Blinky — TMDSCNCD28388D controlCARD
//
// DESCRIPTION:
//   Toggles the onboard user LED (D1, GPIO31) at a 1 Hz rate using a
//   blocking delay loop on CPU1.  The project serves as a baseline hardware
//   verification step: if the LED blinks, the clock tree, GPIO subsystem,
//   and debug connection are all confirmed working before any motor-control
//   firmware is loaded.
//
//   Blink pattern  :  500 ms ON  →  500 ms OFF  →  repeat
//   Active logic   :  LED turns ON when GPIO31 is driven LOW (active-low)
//
// HARDWARE:
//   Board   : TMDSCNCD28388D Rev.B controlCARD
//   Dock    : TMDSHSECDOCK
//   LED D1  : GPIO31  (HSEC connector, pin 82)
//   LED D2  : GPIO34  (HSEC connector — reserved, not driven here)
//
// DEPENDENCIES:
//   C2000Ware  26.01.00.00
//   Compiler   TI C2000 CGT  25.11.0.LTS
//
//#############################################################################
//
// Copyright (C) 2024 Texas Instruments Incorporated - http://www.ti.com
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//
//   Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.
//
//   Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the
//   documentation and/or other materials provided with the distribution.
//
//   Neither the name of Texas Instruments Incorporated nor the names of
//   its contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
//#############################################################################

#include "driverlib.h"
#include "device.h"
#include "board.h"
#include "c2000ware_libraries.h"

void main(void)
{
    //
    // Initialize the device clock tree and all peripheral power domains.
    // This configures the PLL, sets up the CPU frequency, and brings the
    // oscillator to a stable operating point before any peripheral is touched.
    //
    Device_init();

    //
    // Release the GPIO multiplexer from its reset-state lockout and configure
    // the pull-up network.  Must be called before any GPIO register is written.
    //
    Device_initGPIO();

    //
    // Initialize the Peripheral Interrupt Expansion (PIE) module and clear
    // all interrupt flag registers.  This also disables CPU-level interrupts,
    // giving the initialization sequence a clean, deterministic environment.
    //
    Interrupt_initModule();

    //
    // Load the PIE vector table with the default shell ISR addresses supplied
    // by the driverlib startup code.  Any vector not later overridden will
    // safely land in the shell handler.
    //
    Interrupt_initVectorTable();

    //
    // Apply the pin-mux and GPIO direction settings generated by SysConfig.
    // After this call, GPIO31 is configured as a push-pull output and its
    // initial state is set high (LED off).
    //
    Board_init();

    //
    // Initialize any C2000Ware library components included via SysConfig.
    //
    C2000Ware_libraries_init();

    //
    // Unmask the global interrupt flag (INTM) and the debug-override interrupt
    // mask (DBGM) so the CPU can service real-time interrupts through the PIE.
    //
    EINT;
    ERTM;

    //
    // Main loop — blink LED D1 at 1 Hz indefinitely.
    //
    for(;;)
    {
        //
        // Drive GPIO31 low: turns LED D1 on (active-low circuit).
        //
        GPIO_writePin(myBoardLED0_GPIO, 0);
        DEVICE_DELAY_US(500000UL);

        //
        // Drive GPIO31 high: turns LED D1 off.
        //
        GPIO_writePin(myBoardLED0_GPIO, 1);
        DEVICE_DELAY_US(500000UL);
    }
}

//
// End of File
//
