/* Author: Masoud Bakhshi - www.plan22.net */

/*
 * cpu1_adc_ipc - F28388D CPU1 ADC sampler + IPC producer.
 *
 * Samples ADCINA0 (HSEC8 pin 9, dock J4 pin 1) at 10 kHz via ePWM1 SOCA,
 * converts each result to float volts (VREFHI = VDDA = 3.3 V), and writes
 * it into a shared ring buffer that lives in the CPU1_TO_CM MSGRAM bank.
 *
 * The Cortex-M4 (CM) core boots from flash via Device_bootCM(),
 * configures the on-chip Ethernet MAC, and forwards 50 samples per
 * UDP packet to the Raspberry Pi receiver at 192.168.10.20:5005.
 *
 * WARNING:  ADCINA0 absolute maximum is VREFHI (3.3 V) referenced to
 *           VSSA (GND).  Never drive this pin outside 0 .. 3.3 V.
 */

#include <stdint.h>
#include "driverlib.h"
#include "device.h"
#include "board.h"

/*
 * Shared block layout - CPU1 writes, CM reads.
 *
 * Lives in CPU1_TO_CM MSGRAM (C28x addr 0x0003F800, CM addr 0x20080000).
 * Size budget for that bank is 2048 bytes on C28x word addressing.
 * 16-byte header + 128 float ring = 528 16-bit-word equivalent.
 *
 * RING_SIZE must be a power of two so the index can wrap with a mask.
 *
 * IMPORTANT:  Per F2838x memory-access policy the CPU1_TO_CM bank is
 *             write-locked from the CM side.  CM must never store
 *             into this struct.  CM keeps its own consumer index in a
 *             CM-local variable.
 */
#define ADC_SHARED_MAGIC      0xC2000ADCu
#define ADC_RING_SIZE         128u
#define ADC_RING_MASK         (ADC_RING_SIZE - 1u)
#define ADC_NOTIFY_COUNT      50u
#define ADC_SAMPLE_RATE_HZ    10000u

struct adc_shared_block
{
    uint32_t magic;
    uint32_t producer_seq;
    uint32_t sample_rate_hz;
    uint32_t ring_size;
    float    ring[ADC_RING_SIZE];
};

#pragma DATA_SECTION(g_shared, "MSGRAM_CPU_TO_CM")
volatile struct adc_shared_block g_shared;

/* LED D1 = GPIO31 (negative logic, per TMDSCNCD28388D user guide). */
#define LED_D1_GPIO    31

/* Counter for IPC heartbeat (CPU1 -> CM, IPC_FLAG0 every notify_count samples). */
static volatile uint32_t s_isr_count = 0;

__interrupt void adcA1ISR(void);

void main(void)
{
    /*
     * Initialize PLL, clocks and watchdog (configures device for 200 MHz).
     */
    Device_init();

    /*
     * Boot the Cortex-M4 (CM) core from its own flash bank (BANK0 sector 0).
     * The CM image is flashed separately by the cm_ethernet project.
     *
     * BOOTMODE_BOOT_TO_FLASH_SECTOR0 is documented in device.h; the CM
     * BootROM hands control to address 0x00200000 (CM flash bank 0).
     */
#ifdef _FLASH
    Device_bootCM(BOOTMODE_BOOT_TO_FLASH_SECTOR0);
#else
    Device_bootCM(BOOTMODE_BOOT_TO_S0RAM);
#endif

    /*
     * Set Ethernet clock = SYSPLL / 2 = 100 MHz.
     * Must be done BEFORE the CM-side Ethernet driver brings up the MAC.
     */
    SysCtl_setEnetClk(SYSCTL_ENETCLKOUT_DIV_2, SYSCTL_SOURCE_SYSPLL);

    /*
     * Pin-mux the on-chip MII signals to the controlCARD's DP83822 PHY.
     * These pin numbers are fixed by the F2838x silicon; they are
     * configured from CPU1 even though the EMAC itself lives in the CM
     * peripheral domain.
     */
    GPIO_setPinConfig(GPIO_105_ENET_MDIO_CLK);
    GPIO_setPinConfig(GPIO_106_ENET_MDIO_DATA);

    GPIO_setPinConfig(GPIO_109_ENET_MII_CRS);
    GPIO_setPinConfig(GPIO_110_ENET_MII_COL);

    GPIO_setPinConfig(GPIO_75_ENET_MII_TX_DATA0);
    GPIO_setPinConfig(GPIO_122_ENET_MII_TX_DATA1);
    GPIO_setPinConfig(GPIO_123_ENET_MII_TX_DATA2);
    GPIO_setPinConfig(GPIO_124_ENET_MII_TX_DATA3);
    GPIO_setPinConfig(GPIO_118_ENET_MII_TX_EN);

    GPIO_setPinConfig(GPIO_114_ENET_MII_RX_DATA0);
    GPIO_setPinConfig(GPIO_115_ENET_MII_RX_DATA1);
    GPIO_setPinConfig(GPIO_116_ENET_MII_RX_DATA2);
    GPIO_setPinConfig(GPIO_117_ENET_MII_RX_DATA3);
    GPIO_setPinConfig(GPIO_113_ENET_MII_RX_ERR);
    GPIO_setPinConfig(GPIO_112_ENET_MII_RX_DV);

    GPIO_setPinConfig(GPIO_44_ENET_MII_TX_CLK);
    GPIO_setPinConfig(GPIO_111_ENET_MII_RX_CLK);

    /*
     * Release the DP83822 from power-down (GPIO108) and reset (GPIO119).
     * Both pins are held high via internal pull-ups while CPU1 boots,
     * driving them explicitly here makes the post-reset state deterministic
     * and matches TI's ethernet_ipc_ex1_basic example sequence.
     */
    GPIO_setDirectionMode(108, GPIO_DIR_MODE_OUT);
    GPIO_setPadConfig(108, GPIO_PIN_TYPE_PULLUP);
    GPIO_writePin(108, 1);

    GPIO_setDirectionMode(119, GPIO_DIR_MODE_OUT);
    GPIO_setPadConfig(119, GPIO_PIN_TYPE_PULLUP);
    GPIO_writePin(119, 1);

    /*
     * Initialize GPIO mux / ADC / ePWM / interrupts from SysConfig.
     * Board_init() is generated by SysConfig into board.h/board.c.
     */
    Device_initGPIO();
    Board_init();

    /*
     * LED D1 (GPIO31) is set up by SysConfig as an output with negative
     * logic.  Drive it high so the LED is off at boot - the ADC ISR
     * will toggle it as a heartbeat once sampling starts.
     */
    GPIO_writePin(LED_D1_GPIO, 1);

    /*
     * Populate the shared block.  Producer_seq is set last so that the
     * CM core can detect a valid snapshot by checking magic first.
     */
    {
        uint32_t i;
        g_shared.sample_rate_hz = ADC_SAMPLE_RATE_HZ;
        g_shared.ring_size      = ADC_RING_SIZE;
        for(i = 0; i < ADC_RING_SIZE; i++)
        {
            g_shared.ring[i] = 0.0f;
        }
        g_shared.producer_seq = 0;
        g_shared.magic        = ADC_SHARED_MAGIC;
    }

    /*
     * Wait for the CM core to come up.  CM signals readiness by setting
     * IPC_FLAG31.  This one-shot handshake guarantees that CM has
     * latched g_shared.magic before CPU1 begins streaming samples.
     */
    IPC_clearFlagLtoR(IPC_CPU1_L_CM_R, IPC_FLAG_ALL);
    IPC_sync(IPC_CPU1_L_CM_R, IPC_FLAG31);

    /*
     * Enable global interrupts and start ePWM1 SOCA, which begins the
     * 10 kHz ADC sample stream.  ePWM1 timebase is configured in
     * SysConfig; here we simply release the time-base clock.
     */
    EINT;
    ERTM;

    SysCtl_enablePeripheral(SYSCTL_PERIPH_CLK_TBCLKSYNC);
    SysCtl_enablePeripheral(SYSCTL_PERIPH_CLK_EPWM1);

    EPWM_enableADCTrigger(EPWM1_BASE, EPWM_SOC_A);

    /*
     * Idle loop.  All sampling work happens in the ADC ISR.
     */
    for(;;)
    {
        __asm(" IDLE");
    }
}

/*
 * ADC-A interrupt 1 (end of conversion of SOC0).
 *
 * Wired up in SysConfig as adc1.adcInt1.interruptHandler = "adcA1ISR".
 *
 * Hot path - keep this short.  Steps:
 *   1. read raw 12-bit result
 *   2. scale to volts using VREFHI = 3.3 V
 *   3. publish into ring slot
 *   4. increment producer_seq (release-style write: ring slot first,
 *      then producer_seq, so CM never observes a partial value)
 *   5. clear ADC INT1 flag and ePWM1 SOCA overflow
 *   6. every ADC_NOTIFY_COUNT samples, raise IPC_FLAG0 so CM knows to
 *      check the ring even if its 1 ms SysTick has not fired yet
 *   7. toggle LED D1 every 5000 samples (~2 Hz heartbeat)
 */
__interrupt void adcA1ISR(void)
{
    uint16_t raw   = ADC_readResult(ADCARESULT_BASE, ADC_SOC_NUMBER0);
    float    volts = ((float)raw * 3.3f) / 4095.0f;

    uint32_t seq   = g_shared.producer_seq;
    uint32_t slot  = seq & ADC_RING_MASK;

    g_shared.ring[slot] = volts;

    /*
     * Memory order matters:  the ring slot store above must be
     * globally visible before producer_seq is incremented, because CM
     * polls producer_seq and then reads the ring.  The C28x core
     * retires stores in program order to the local bus, and the MSGRAM
     * controller propagates them to CM in the same order, so a simple
     * write of producer_seq+1 is sufficient.  No explicit barrier is
     * available on C28x.
     */
    g_shared.producer_seq = seq + 1u;

    s_isr_count++;
    if((s_isr_count % ADC_NOTIFY_COUNT) == 0u)
    {
        /*
         * Pulse IPC_FLAG0 to CM.  CM also polls producer_seq on its
         * SysTick, so this flag is a best-effort wake-up - if CM is
         * already inside its main loop it will pick up the new
         * samples on the next tick.
         */
        IPC_setFlagLtoR(IPC_CPU1_L_CM_R, IPC_FLAG0);
    }

    if((s_isr_count & 0x1FFFu) == 0u)
    {
        GPIO_togglePin(LED_D1_GPIO);
    }

    ADC_clearInterruptStatus(ADCA_BASE, ADC_INT_NUMBER1);
    Interrupt_clearACKGroup(INTERRUPT_ACK_GROUP1);
}
