/* Author: Masoud Bakhshi - www.plan22.net */
/*
 * adc_init.c
 *
 * ADCA and ADCB bring up. The current sense channels live on ADCA
 * (SOC0/SOC1/SOC2) and the Vdc channel on ADCB (SOC0). All four
 * conversions are launched from a single SOCA pulse generated by
 * ePWM1 at TBCTR = 0. ADCA1 EOC of the last channel (SOC2) is
 * routed to the PIE as the control ISR source.
 */

#include "adc_iface.h"
#include "user_config.h"
#include "board_pinmap_boostxl_3phganinv.h"
#include "driverlib.h"
#include "device.h"

/*
 * adc_module_init
 * Purpose : Common configuration for one ADC module: 12-bit single
 *           ended, ADCCLK = SYSCLK / 4, INT pulse on EOC.
 * Inputs  : base  ADC module base address
 * ISR safe: no
 */
static void adc_module_init(uint32_t base)
{
    ADC_setMode(base, ADC_RESOLUTION_12BIT, ADC_MODE_SINGLE_ENDED);
    ADC_setPrescaler(base, ADC_CLK_DIV_4_0);
    ADC_setInterruptPulseMode(base, ADC_PULSE_END_OF_CONV);
    ADC_enableConverter(base);
    DEVICE_DELAY_US(1000);
}

void adc_iface_init(void)
{
    /* F2838x defaults to the internal 3.3 V VREF after reset. No
     * additional reference selection call is needed; see
     * ADC_VREF_V in user_config.h for the scaling constant used by
     * the conversion macros.
     */
    adc_module_init(ADCA_BASE);
    adc_module_init(ADCB_BASE);

    /* ADCA: IFB_A on SOC0, IFB_B on SOC1, IFB_C on SOC2.
     * 75 ns sample window: at SYSCLK = 200 MHz and ADCCLK = SYSCLK/4
     * = 50 MHz, one ADCCLK = 20 ns. ACQPS = 14 -> 15 ADCCLK = 300 ns
     * which is the recommended minimum on F2838x for SAR conversion.
     */
    ADC_setupSOC(ADC_IFB_A_BASE, ADC_IFB_A_SOC, ADC_TRIGGER_EPWM1_SOCA,
                 ADC_IFB_A_CHAN, 14u);
    ADC_setupSOC(ADC_IFB_B_BASE, ADC_IFB_B_SOC, ADC_TRIGGER_EPWM1_SOCA,
                 ADC_IFB_B_CHAN, 14u);
    ADC_setupSOC(ADC_IFB_C_BASE, ADC_IFB_C_SOC, ADC_TRIGGER_EPWM1_SOCA,
                 ADC_IFB_C_CHAN, 14u);

    /* ADCB: Vdc on SOC0. */
    ADC_setupSOC(ADC_VDC_BASE, ADC_VDC_SOC, ADC_TRIGGER_EPWM1_SOCA,
                 ADC_VDC_CHAN, 14u);

    /* EOC interrupt wired to ADCA SOC2 = the last conversion. */
    ADC_setInterruptSource(ADC_EOC_BASE, ADC_EOC_INT_NUMBER,
                           ADC_EOC_SOC_TRIG);
    ADC_enableInterrupt(ADC_EOC_BASE, ADC_EOC_INT_NUMBER);
    ADC_clearInterruptStatus(ADC_EOC_BASE, ADC_EOC_INT_NUMBER);
}
