/* Author: Masoud Bakhshi - www.plan22.net */
/*
 * pwm_init.c
 *
 * ePWM1/2/3 bring up for symmetric center aligned SVPWM at 20 kHz.
 * ePWM1 is the master, ePWM2 and ePWM3 are phase synchronized with
 * zero phase shift so all three legs reload CMPA simultaneously.
 */

#include "pwm_iface.h"
#include "user_config.h"
#include "board_pinmap_boostxl_3phganinv.h"
#include "driverlib.h"
#include "device.h"

/*
 * pwm_one_leg_init
 * Purpose : Configure one ePWM module as a leg of the inverter.
 *           Up/down count, period set from PWM_TBPRD_TICKS, shadow
 *           load CMPA at CTR = ZRO, complementary outputs with dead
 *           band, action: EPWMxA goes high on up-count compare,
 *           EPWMxB is the inverted dead-banded copy generated by the
 *           dead band sub-module.
 * Inputs  : base   ePWM module base address
 *           is_master  set to true for ePWM1 (drives the sync chain)
 * ISR safe: no
 */
static void pwm_one_leg_init(uint32_t base, bool is_master)
{
    /* Time base. */
    EPWM_setTimeBaseCounterMode(base, EPWM_COUNTER_MODE_UP_DOWN);
    EPWM_setTimeBasePeriod(base, PWM_TBPRD_TICKS);
    EPWM_setTimeBaseCounter(base, 0);
    EPWM_setClockPrescaler(base,
                           EPWM_CLOCK_DIVIDER_1,
                           EPWM_HSCLOCK_DIVIDER_1);

    /* Phase sync. ePWM1 drives the sync chain; the others receive. */
    if (is_master)
    {
        EPWM_disablePhaseShiftLoad(base);
        EPWM_enableSyncOutPulseSource(base, EPWM_SYNC_OUT_PULSE_ON_CNTR_ZERO);
    }
    else
    {
        EPWM_enablePhaseShiftLoad(base);
        EPWM_setPhaseShift(base, 0u);
        EPWM_setCountModeAfterSync(base, EPWM_COUNT_MODE_UP_AFTER_SYNC);
    }

    /* Compare A: shadow load at CTR = ZRO so duty changes are atomic. */
    EPWM_setCounterCompareShadowLoadMode(base,
                                         EPWM_COUNTER_COMPARE_A,
                                         EPWM_COMP_LOAD_ON_CNTR_ZERO);
    EPWM_setCounterCompareValue(base, EPWM_COUNTER_COMPARE_A,
                                (uint16_t)(PWM_TBPRD_TICKS / 2u));

    /* Action qualifier: classic center aligned high side waveform.
     * EPWMxA = HIGH when CTR == CMPA on up-count,
     *          LOW  when CTR == CMPA on down-count.
     */
    EPWM_setActionQualifierAction(base, EPWM_AQ_OUTPUT_A,
                                  EPWM_AQ_OUTPUT_HIGH,
                                  EPWM_AQ_OUTPUT_ON_TIMEBASE_UP_CMPA);
    EPWM_setActionQualifierAction(base, EPWM_AQ_OUTPUT_A,
                                  EPWM_AQ_OUTPUT_LOW,
                                  EPWM_AQ_OUTPUT_ON_TIMEBASE_DOWN_CMPA);

    /* Dead band: active-high complementary. RED on EPWMxA, FED on
     * EPWMxB inverted output.
     */
    EPWM_setDeadBandControlShadowLoadMode(base, EPWM_DB_LOAD_ON_CNTR_ZERO);
    EPWM_setDeadBandDelayMode(base, EPWM_DB_RED, true);
    EPWM_setDeadBandDelayMode(base, EPWM_DB_FED, true);
    EPWM_setDeadBandDelayPolarity(base, EPWM_DB_RED, EPWM_DB_POLARITY_ACTIVE_HIGH);
    EPWM_setDeadBandDelayPolarity(base, EPWM_DB_FED, EPWM_DB_POLARITY_ACTIVE_LOW);
    EPWM_setRisingEdgeDeadBandDelayInput(base, EPWM_DB_INPUT_EPWMA);
    EPWM_setFallingEdgeDeadBandDelayInput(base, EPWM_DB_INPUT_EPWMA);
    EPWM_setRisingEdgeDelayCount(base, DEADTIME_RED_TICKS);
    EPWM_setFallingEdgeDelayCount(base, DEADTIME_FED_TICKS);

    /* Trip zone: gate forced low when TZ trip fires. The actual TZ
     * source assignment (one-shot from OC/OV) is wired up by the
     * safety module.
     */
    EPWM_setTripZoneAction(base, EPWM_TZ_ACTION_EVENT_TZA, EPWM_TZ_ACTION_LOW);
    EPWM_setTripZoneAction(base, EPWM_TZ_ACTION_EVENT_TZB, EPWM_TZ_ACTION_LOW);
}

/*
 * pwm_setup_socb_trigger
 * Purpose : Configure ePWM1 to generate SOCA on TBCTR = 0 (carrier
 *           valley). This is the standard sampling point for low side
 *           current sensing because at the valley the low side device
 *           is on and the INA240 sees the actual phase current.
 * ISR safe: no
 */
static void pwm_setup_soca_trigger(void)
{
    EPWM_setADCTriggerSource(PWM_LEG_A_BASE, EPWM_SOC_A,
                             EPWM_SOC_TBCTR_ZERO);
    EPWM_setADCTriggerEventPrescale(PWM_LEG_A_BASE, EPWM_SOC_A, 1);
    EPWM_enableADCTrigger(PWM_LEG_A_BASE, EPWM_SOC_A);
}

void pwm_iface_init(void)
{
    /* GPIO mux to ePWM outputs. */
    GPIO_setPinConfig(GPIO_0_EPWM1A);
    GPIO_setPinConfig(GPIO_1_EPWM1B);
    GPIO_setPinConfig(GPIO_2_EPWM2A);
    GPIO_setPinConfig(GPIO_3_EPWM2B);
    GPIO_setPinConfig(GPIO_4_EPWM3A);
    GPIO_setPinConfig(GPIO_5_EPWM3B);

    /* Per-leg configuration. */
    pwm_one_leg_init(PWM_LEG_A_BASE, true);
    pwm_one_leg_init(PWM_LEG_B_BASE, false);
    pwm_one_leg_init(PWM_LEG_C_BASE, false);

    /* ADC sample trigger. */
    pwm_setup_soca_trigger();

    /* Start outputs in the safe coast state (50 percent duty). */
    pwm_iface_force_idle(PWM_TBPRD_TICKS);

    /* Force a one-shot trip so the gates are off until the user enables.
     * The user enable path clears this via pwm_iface_enable_outputs.
     */
    pwm_iface_disable_outputs();
}

void pwm_iface_enable_outputs(void)
{
    EPWM_clearTripZoneFlag(PWM_LEG_A_BASE, EPWM_TZ_INTERRUPT | EPWM_TZ_FLAG_OST);
    EPWM_clearTripZoneFlag(PWM_LEG_B_BASE, EPWM_TZ_INTERRUPT | EPWM_TZ_FLAG_OST);
    EPWM_clearTripZoneFlag(PWM_LEG_C_BASE, EPWM_TZ_INTERRUPT | EPWM_TZ_FLAG_OST);
}

void pwm_iface_disable_outputs(void)
{
    EPWM_forceTripZoneEvent(PWM_LEG_A_BASE, EPWM_TZ_FORCE_EVENT_OST);
    EPWM_forceTripZoneEvent(PWM_LEG_B_BASE, EPWM_TZ_FORCE_EVENT_OST);
    EPWM_forceTripZoneEvent(PWM_LEG_C_BASE, EPWM_TZ_FORCE_EVENT_OST);
}
